### ISSUE TITLE
Баг: на iPhone 5 прячется поле e-mail'а

### ISSUE THREAD

**Issue by golubev** [sergei-zelinsky/LUN.UA-Questionnaire#1]
На iPhone 5 прячется поле e-mail'а. Когда ставишь фокус на это поле и начинаешь что-то вводить, то само поле не видно за клавиатурой. Передвинуть страницу возможности нету.

![image](https://cloud.githubusercontent.com/assets/951364/18795452/4d2ad116-81cd-11e6-9a6a-b3a45ba80b80.png)

**Comment by sergei-zelinsky** [comment]
Нет возможности протестировать на iPhone 5.
Прокрутка страницы доступна на следующем устройстве.
Скриншот (устройство DOOGEE X6, браузер Chrome Mobile)
![image](https://cloud.githubusercontent.com/assets/19428086/18872065/2afea878-84c1-11e6-881d-4bbbd0f679fc.png)
