### ISSUE TITLE
Баг: съезжает навигация

### ISSUE THREAD

**Issue by golubev** [sergei-zelinsky/LUN.UA-Questionnaire#2]
"Съехали" кнопки навигации снизу.

См. напр. (iPhone 5)

![image](https://cloud.githubusercontent.com/assets/951364/18795498/90072e12-81cd-11e6-80f9-2591adea0a34.png)

**Comment by sergei-zelinsky** [comment]
Проблема решена. 
Нет возможности протестировать на реальном устройстве. 
Скриншот (эмулятор iPhone 5, браузер Chrome).
![localhost-8080- iphone 5](https://cloud.githubusercontent.com/assets/19428086/18847657/b35cb7a2-8433-11e6-82a1-fccc46bc14e7.png)
