### ISSUE TITLE
Баг: фотографии показываются не полностью на мобильном

### ISSUE THREAD

**Issue by golubev** [sergei-zelinsky/LUN.UA-Questionnaire#4]
В мобильной версии (iPhone 5) фотографии показываются не полностью. Адаптивность должна быть реализована путем вывода изображений в столбик.

![image](https://cloud.githubusercontent.com/assets/951364/18795616/089c9c18-81ce-11e6-8f37-e2df1329ca61.png)

**Comment by sergei-zelinsky** [comment]
Ошибка исправлена.

**Comment by golubev** [comment]
Хорошо. Это уже выложено на твой тестовый домен?

**Comment by sergei-zelinsky** [comment]
Да. Я обновил файлы на тестовом домене.
