### ISSUE TITLE
Пожелание: убрать увеличения сайта при фокусе поля

### ISSUE THREAD

**Issue by golubev** [sergei-zelinsky/LUN.UA-Questionnaire#5]
Когда я в мобильном Google Chrome на iPhone ставлю фокус на поле - увеличивается масштаб просмотра сайта (сайт приближается). Если начать заполнять форму это порядком мешает, т.к. сайт "двигается" без моего на то желания. Хочется чтобы сайт не двигался по фокусу поля ввода, т.е. не менялся масштаб просмотра сайта.

**Comment by sergei-zelinsky** [comment]
Исправлено.

**Comment by golubev** [comment]
На хроме продолжает, в Сафари не увеличивает. Спасибо!
